### ISSUE TITLE
popup (screen) preloading

### ISSUE THREAD

**Issue by AGulev** [britzl/monarch#19]
Would be great to have possability to preload some screen or popup manualy before using.
For example: I have a heavy win-popup, and I want to load  it when level loads, and then just use it without loading lag when it's need and unload after using.

What do you think about it?

**Comment by britzl** [comment]
What happens if you async_load a collection and then try and async_load it again? Do you still get a proxy_loaded message the second time? If you do, then it should be enough that you async_load it manually and then use Monarch as normal. If you don't get a proxy_loaded message the second time then we need to come up with another solution. Two options:

1. async_load the collection manually and indicate this when calling `monarch.show(hash("myscreen"), { preloaded = true })`
2. Add `monarch.preload(hash("myscreen"))`

**Comment by AGulev** [comment]
> What happens if you async_load a collection and then try and async_load it again?

I receive next message:

ERROR:GAMESYS: The collection /collections/popups/win_chest/win_chest.collectionc could not be loaded since it was already. Message 'async_load' sent from main_menu:/menu#main_menu to loader:/win_chest#.

> Add monarch.preload(hash("myscreen"))

I think it may be great solution

**Comment by britzl** [comment]
Added monarch.preload(screen_id, [callback]).

https://github.com/britzl/monarch/releases/tag/2.6.0

**Comment by AGulev** [comment]
Thats awesome! Thank you!

**Comment by AGulev** [comment]
@britzl 
I think here need adding checking for already preloaded screens for avoiding 
>The collection could not be loaded since it was already. Message 'async_load' sent from loader:/win_chest#screen to loader:/win_chest#collectionproxy.


```
function M.preload(id, cb)
	assert(id, "You must provide a screen id")
	id = tohash(id)
	assert(screens[id], ("There is no screen registered with id %s"):format(tostring(id)))

	local screen = screens[id]
        if screen.preloaded then
             if cb then cb() end
             return
        end
	local co
	co = coroutine.create(function()
		screen.co = co
		change_context(screen)
		screen.wait_for = PROXY_LOADED
		msg.post(screen.proxy, ASYNC_LOAD)
		coroutine.yield()
		screen.preloaded = true
		screen.wait_for = nil
		if cb then cb() end
	end)
	coroutine.resume(co)
end
```
