### ISSUE TITLE
Add option to not add a screen to the stack

### ISSUE THREAD

**Issue by britzl** [britzl/monarch#26]
Perhaps one of:

* monarch.show("myscreen", { no_stack = true })
* monarch.show("myscreen", { clear_stack = true })

**Comment by britzl** [comment]
Hmm, now that I read this feature request it makes no sense. How would it be supposed to work if the screen isn't added to the stack? How would you hide it and what would be shown after it is hidden? The screen needs to be on the stack.

@AGulev was it you who requested this?

**Comment by AGulev** [comment]
Hey @britzl , 
I am not sure that it was me, but I think it may be useful.

For example I use manual load for background collection in Onet Paradise game, because I don't need any interactions with the background. If I try to load this collection using monarch it will be hided when I change screen, but I want to use this background everywhere and didn't hide.

Not sure that this work for screen manager, but I am sure that it would be useful for me in some cases for standardisation of collection-proxy loading in some projects.

@programmerby maybe it was your request?
