### ISSUE TITLE
Using of factory popup inside collection proxy screen

### ISSUE THREAD

**Issue by AGulev** [britzl/monarch#35]
I have a lot of popups, and I wanna use a few of them as screen_factory inside colection (screen_proxy).  Is it possible?
For now, If I try to make it I have a problem with input focus.

**Comment by britzl** [comment]
Would you mind creating a minimal example showing the problem? It's easier for me to experiment with and try to find a fix if I have a project to test it on.

**Comment by AGulev** [comment]
yes, of course. I'll do that.

**Comment by AGulev** [comment]
[example.zip](https://github.com/britzl/monarch/files/2709074/example.zip)

Example. 
First popup when you tap "start game" (now this popup in menu.collection) inputs doesn't work.

**Comment by britzl** [comment]
Ok, I see where the problem is. In the example we have the following structure:

```
bootstrap collection
|
+-menu (screen proxy)
  |
  +-go
  | |
  | +-menu.gui (w. menu.gui_script)
  |
  +-popup (screen factory)
```

When the menu is shown Monarch will acquire input focus for the `menu` proxy and the `menu.gui_script` will acquire input focus for the gui itself. When `popup` is shown Monarch will release input focus for the previous screen `menu` and acquire input for `popup`. This means that input will not propagate to the `popup` since the `menu` proxy has lost input focus (this is how input for collection proxies work in Defold).

One workaround could be to have a `parent_id` property on the `screen_proxy.script` and `screen_factory.script` so that Monarch knows that a screen is a child/sub-screen of another screen. If that is the case Monarch could keep focus for the parent screen when the child is shown. The problem with this in the example is that `menu.gui_script` still has focus which means that it is possible to interact with the menu while the popup is shown... This could be solved in the `menu.gui_script` by releasing input focus when getting a focus lost message.

Another possible solution would be to use a collection factory instead of a proxy for the menu. But for this to be a good solution Monarch would also need to support "Load Dynamically" for screen factories (which would be a nice feature anyway!).

**Comment by britzl** [comment]
I think the solution for this case is to make sure that the parent screen is a collection factory created screen and not a proxy. I can't see any other clean solution. I'll make a note of this in the documentation.
