### ISSUE TITLE
Stalls on showing first screen

### ISSUE THREAD

**Issue by Jerakin** [britzl/monarch#45]
I am trying to show a screen but the screen is not shown.

The `monarch.show("menu")` goes as far as
`show_in(screen, top, options and options.reload, add_to_stack, callbacks.track())`
but doesn't enter the function.

Something seems to be wrong with `top`, because simply doing `print(top)` stalls it. If I change the line to `show_in(screen, nil, options and options.reload, add_to_stack, callbacks.track())` the screen shows fine.

The debugger says that top doesn't exists (which makes sense because even if there is a top it is only defined in the local scope of the coroutine right?)

**Comment by Jerakin** [comment]
The odd thing is that I have used monarch in this way before without problems

**Comment by britzl** [comment]
Weird. Can you share a project where I can test this myself?

**Comment by Jerakin** [comment]
https://github.com/Jerakin/WordDrop/commit/981f79b8095e68dfd11b74f3656880c2563e5685

**Comment by britzl** [comment]
Ok, so it's the superstrict module that detects unknown global access to top in the show_in() function. For some reason it doesn't throw an error though. Actually that's because the show_in code is run in a coroutine and monarch doesn't properly print all errors. I will fix this and the top problem in Monarch ASAP.

**Comment by britzl** [comment]
Fixed in https://github.com/britzl/monarch/releases/tag/2.17.2
